---
- name: (IOS) Apply description and enable SVI interfaces
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ item.name }}"
      description: "{{ item.description }}"
      enabled: "{{ item.enabled }}"
  loop: "{{ vlan_interfaces }}"
  when: ansible_network_os == "ios"

- name: (IOS) Configure SVI IP Address
  cisco.ios.ios_l3_interfaces:
    config:
    - name: "{{item.name}}"
      ipv4:
      - address: "{{ item.address }}"
  loop: "{{ vlan_interfaces }}"
  when: ansible_network_os == "ios"

- name: (NX-OS) Enable interface VLAN feature
  cisco.nxos.nxos_feature:
    feature: interface-vlan
    state: enabled
  when: ansible_network_os == "nxos"

- name: (NX-OS) Apply description and enable SVI interfaces
  cisco.nxos.nxos_interfaces:
    config:
    - name: "{{ item.name }}"
      description: "{{ item.description }}"
      enabled: "{{ item.enabled }}"
  loop: "{{ vlan_interfaces }}"
  when: ansible_network_os == "nxos"

- name: (NX-OS) Configure IP on interfaces
  cisco.nxos.nxos_l3_interfaces:
    config:
    - name: "{{item.name}}"
      ipv4:
      - address: "{{ item.address }}"
  loop: "{{ vlan_interfaces }}"
  when: ansible_network_os == "nxos"