---
- hosts: switches
  gather_facts: false
  
  tasks:
  - name: (IOS) Configure VLAN interfaces
    cisco.ios.ios_vlans:
      config:
      - name: "{{ item.vlan_name }}"
        vlan_id: "{{ item.vlan_id }}"
        enabled: "{{ item.vlan_enabled }}"
    loop: vlans
    when: ansible_network_os == "ios"
  
  - name: (NX-OS) Configure VLAN interfaces
    cisco.nxos.nxos_vlans:
      config:
      - name: "{{ item.vlan_name }}"
        vlan_id: "{{ item.vlan_id }}"
        enabled: "{{ item.vlan_enabled }}"
    loop: vlans
    when: ansible_network_os == "nxos"