    switches:
      hosts:
        cat9kv_sw1:
          switchport_interfaces:
          - name: "GigabitEthernet1/0/1"
            description: "Alpine-0 Desktop"
            enabled: True
            vlan_id: 5
          - name: "GigabitEthernet1/0/8"
            description: "Uplink to cat8kv_rtr1_G2"
            enabled: True
            vlan_id: 5
          vlan_interfaces:
          - name: "vlan5"
            address: "2.2.2.253/24"
            description: "VLAN_5 SVI"
            enabled: True
        cat9kv_sw2:
          switchport_interfaces:
          - name: "GigabitEthernet1/0/1"
            description: "Alpine-1 Desktop"
            enabled: True
            vlan_id: 20
          - name: "GigabitEthernet1/0/8"
            description: "Uplink to cat8kv_rtr2_G2"
            enabled: True
            vlan_id: 20
          vlan_interfaces:
          - name: "vlan20"
            description: "VLAN_20 SVI"
            address: "4.4.4.125/25"
            enabled: True
        n9kv_sw1:
          switchport_interfaces:
          - name: "Ethernet1/1"
            description: "Uplink to cat8kv_rtr_G3"
            vlan_id: 30
            enabled: True
          - name: "Ethernet1/2"
            description: "Alpine-2 Desktop"
            enabled: True
            vlan_id: 30
          vlan_interfaces:
          - name: "vlan30"
            description: "VLAN_30 SVI"
            address: "4.4.4.253/25"
            enabled: True